### ISSUE TITLE
Reorganize reports sidebar 

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#113]
- [x] Remove right sidebar (Help and About/Info will be on the top bar)
- [x] Report button will be floating above map
- [x] Report button will show/hide Report Overview with results
- [x] When Report Overview is empty, add text `Please complete a workflow to see results`
- [x] Add Print button below Report Overview title (#80)
- [x] Add Download all button next to Print button (#79)
- [x] Add Report 'cards' for individual completed workflow results (#83)
- [x] Change floating Report icon to stacked cards
- [x] Add 'download' button to report cards
- [ ] Add ability to edit report card title
- [ ] Add ability to remove card from report 

Images below for reference

![image](https://user-images.githubusercontent.com/40237491/140788750-1b22dee8-e16f-4195-8add-27fcee1de55d.png)

![image](https://user-images.githubusercontent.com/40237491/140791115-8d483b24-fdcc-46a4-ae7b-9e24ad46ac1f.png)

**Comment by HansVraga** [comment]
Just made some edits to (hopefully) better define discrete 'tasks' - (@amedenblik , @mitchas ) feel free to split out if this one issue is too big as well

**Comment by harper-wavra** [comment]
Fixed with Mitch's workflow branch & issue #145
