### ISSUE TITLE
Beta release checklist

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#128]
Review the following items in preparation for Beta release. For each item, check off if complete, link to an open issue to complete the item, or indicate if the item is being skipped and provide an explanation. 

- [x] Load Test `Not applicable for beta release`
- [x] Google Analytics:
     - [x] If a WMA application, add to the WMA Internal Analytics page: https://github.com/USGS-VIZLAB/internal-analytics (see ReadMe). You can make a pull request with changes to this yaml file: https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/gaTable.yaml#L779 with whatever new IDs and views the dashboard should include for those applications `Not applicable for beta release`
     - [x] Configured for USA Analytics: https://analytics.usa.gov/ `Not applicable for beta release`
- [x] Browsers supported / not supported accounted for:
     - [x] Microsoft Edge
     - [x] Chrome (Desktop)
     - [x] Chrome (Android)
     - [x] Firefox
     - [x] Safari (iOS)
     - [x] Safari (OSX): #154
- [x] Monitoring configured: http://wim.usgs.gov/status/
     - [x] Uptime Bot: https://github.com/USGS-WiM/wim-infrastructure/wiki/Monitoring-with-Uptimebot-and-FGDC-status-checker: #152 
     - [x] FGDC status-checker (update the XML wimMapServices): https://github.com/USGS-WiM/service_lists/tree/master/mapServices_xml `No Map services part of this effort to monitor`
- [x] Infrastructure reviewed/documented 
     - [x] https:// enabled
     - [x] Backups enabled
     - [x] (ArcServer) Map Services are tuned: https://github.com/USGS-WiM/wim-infrastructure/wiki/ArcEnterprise:-Tuning-your-Map-Services `No Map services part of this effort to monitor`
- [x] A&A requirements reviewed/documented
- [x] GitHub repo configured: #155
     - [x] Version tags implemented
     - [x] Follow guidelines established by WimPo: https://github.com/USGS-WiM/wimpo
- [x] Application Requirements
     - [x] Favicon
     - [x] About page credits libraries/partners appropriately #156
     - [x] Any 3rd party license disclaimers we need to include
     - [x] Any tokens or other credentials handled appropriately (not in codebase)
     - [x] Public web/map service URLs are given somewhere in the interface/documentation #157
     - [x] Current version displayed in application
     - [x] For interactive Maps, have Gary do a cartographic review `Not applicable for beta release`
     - [x] Appropriate USGS disclaimers: https://www2.usgs.gov/fsp/fsp_disclaimers.asp
- [x] (If initial release, or substantial upgrade) Has USGS Communications (or WSC Communications) been engaged to announce the release of a new product/feature? `Not applicable for beta release`
- [x] Featured on WIM Website: https://wim.usgs.gov/#/projects
- [x] Review for WIM branding (watch out for “WiM”)
- [x] Is the documentation in wimfo for this app/project up-to-date? https://github.com/USGS-WiM/wimfo/tree/dev/Projects #158
- [x] Do we meet the USGS release standards for this application? https://www2.usgs.gov/usgs-manual/im/IM-OSQI-2016-01.html 
     - [x] Web standards: https://www2.usgs.gov/usgs-manual/600/601-1.html
     - [x] 508 Compliance #159
     - [x] All required metadata `Not applicable for beta release`
     - [x] IPDS Approval Process complete `Not applicable for beta release`
     - [x] DOI numbers issued: look at IPDS? https://www1.usgs.gov/csas/doi/  `Not applicable for beta release`
     - [x] Author(s) profile page updated (Drupal) `Not applicable for beta release`
- [x] Update code.json #160
- [x] Create beta URL: #153 
    
Reference: https://github.com/usgs/best-practices
